colunasOcultas = [
    "STATUS",
    "DATA INCLUSÃO",
    "ÚLTIMA ATUALIZAÇÃO",
    "ENVIADO PARA ROTA",
    "ROTA",
    "ÚLTIMO ACESSO_1",
    "CRIADO POR_2",
    "NOME PACIENTE_5",
    "CPF_7",
    "CARTÃO SUS_8",
    "MUNICÍPIO RESIDÊNCIA_10",
    "ENDEREÇO_11",
    "TELEFONE CONTATO_12",
    "OBSERVAÇÃO_13",
    "BAIRRO DO ACIDENTE_6",
    "MEMBROS AFETADOS_7",
    "LADO DO CORPO_8",
    "LOGIN_INCLUSAO",
    "DATA_INCLUSAO",
    "LOGIN_ULTIMA_ATUALIZACAO",
    "DATA_ULTIMA_ATUALIZACAO",
    "TIPO ACIDENTE_4"
]

colunasRenomeadas = {
    "UNIDADE_3": "UNIDADE",
    "DATA NASCIMENTO_6": "DATA NASCIMENTO",
    "SEXO_9": "SEXO",
    "DATA DO ACIDENTE_1": "DATA DO ACIDENTE",
    "HORA DO ACIDENTE_2": "HORA DO ACIDENTE",
    "VEÍCULO(S) ENVOLVIDO(S)_3": "VEÍCULOS ENVOLVIDOS",
    "MUNICÍPIO ACIDENTE_5": "MUNICÍPIO ACIDENTE"
}